#!/bin/bash
# My first script

#Set variables. Temporal human readable, machine readable.
TEMPORAL_MR=$(date '+%s')
TEMPORAL_HR=$(date "+%x, %r")

# Commit to the main project
#git commit -a -m "$1" || exit

BRANCH=`git status -b -s | sed -e "s/^##//" | head -n1`
MESSAGE=`git log --oneline -n1`
DEST_DIR=build-`git describe --always`

# Go into Middleman directory and make build
middleman build

# Rename build directory and copy to github pages project
mv build $DEST_DIR
mv $DEST_DIR *.github.com

# Go into github pages project and append link to build directory to end of file.
pushd *.github.com
echo "<a href=\"$DEST_DIR/index.html\" class=\"temporal\">$TEMPORAL_HR</a><span class=\"commit-m\"> - $BRANCH@$MESSAGE</span><br>" >> index.html

# Push github pages project and exit directory.
git add *
git commit -m "snapshot $BRANCH@$DEST_DIR"
git push origin master
popd

# Push main project.
git push origin master
